version: "3.9"

services:
  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      - CB_HOST
      - CB_USER
      - CB_PSWD
    container_name: todo-mm


  db:
    image: couchbase/server-sandbox:7.0.0
    ports:
      - "8091-8095:8091-8095"
      - "9102:9102"
      - "11210:11210"
    expose:
      - "8091"
      - "8092"
      - "8093"
      - "8094"
      - "8095"
      - "9102"
      - "11210"
